[workspace]
resolver = "3"
members = ["crates/prism-core", "crates/prism-cli", "crates/prism-wasm"]

[workspace.package]
version = "2.0.0"
edition = "2024"
license = "MIT"
authors = ["everywhxn"]
repository = "https://github.com/RSXGroup/prism"
rust-version = "1.85"

[workspace.dependencies]
prism-core = { path = "crates/prism-core", version = "2.0.0" }

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
panic = "abort"
